#
# Since Molecule requires that we specify "image" in the molecule.yml
# file (it will throw an error if it's not specified), we might as well
# use the value specified there; with that said, this has only been
# tested to work with "ubuntu:18.04".
#
FROM {{ item.image }}

ENV container docker

#
# Packages required by Molecule:
#
#  * ca-certificates
#  * bash
#  * python
#  * sudo
#
# Packages required by Systemd:
#
#  * systemd
#
# Packages required by the Ansible role:
#
#  * openssh-server
#
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        ca-certificates \
        bash \
        python \
        openssh-server \
        sudo \
        systemd \
    && apt-get clean \
    && rm -Rf /var/lib/apt/lists/*

#
# In order to test and verify service manipulation via Molecule, we need
# to run Systemd inside of the container. The following are all required
# for Systemd to properly operate in the container.
#
RUN systemctl set-default multi-user.target
VOLUME ["/sys/fs/cgroup"]
CMD ["/lib/systemd/systemd"]
