---
language: python
services: docker

branches:
  only:
    - master

install:
  - pip install docker molecule

script:
  - cd ansible/roles/prakashsurya.host-buttercup
  - travis_wait molecule test
