---
#
# Here we install "lightdm" as the desktop manager (providing the login
# screen) and "elementary" as the desktop environment (providing the
# environment after login).
#
- apt_repository:
    repo: ppa:elementary-os/stable

- apt:
    name:
      - lightdm
      - elementary-desktop
    state: present

#
# This file configures lightdm such that the "ps" user will be logged in
# automatically when the service starts (e.g. when the system boots).
#
- copy:
    dest: /etc/lightdm/lightdm.conf
    owner: root
    group: root
    mode: 0644
    content: |
      [SeatDefaults]
      user-session=pantheon
      autologin-user=ps

- service:
    name: lightdm
    enabled: true
