---
- import_tasks: dhcp-wired.yml
- import_tasks: elementary.yml
- import_tasks: gollum.yml
- import_tasks: hub.yml
- import_tasks: openfortivpn.yml
- import_tasks: misc-pkgs.yml
- import_tasks: pyenv.yml
- import_tasks: slack.yml
- import_tasks: spotify.yml
- import_tasks: vagrant.yml
- import_tasks: zoom.yml

#
# This task file depends on certain groups existing that will be created
# via other task files. Thus, we put this last, to ensure these groups
# will exist before they're used to configure the users.
#
- import_tasks: users.yml
