---
- apt_key:
    keyserver: keyserver.ubuntu.com
    id: 931FF8E79F0876134EDDBDCCA87FF9DF48BF1C90

- apt_repository:
    repo: 'deb http://repository.spotify.com stable non-free'
    state: present
    filename: spotify.list

- apt:
    name: spotify-client
    state: present
