---
dependencies:
 #
 # Provides security-related configurations for ssh.
 #
 - role: dev-sec.ssh-hardening
   # tasks/users.yml will create this user
   ssh_allow_users: ps
   # required for systemd "--user" services
   ssh_use_pam: true
   # allow ssh client to use password based authentication
   ssh_client_password_login: true
 #
 # Enables unattened upgrades; e.g. to install security updates.
 #
 - role: jnv.unattended-upgrades
   # don't reboot system if any upgraded package requires it
   unattended_automatic_reboot: false
   # do automatic removal of new unused dependencies after the upgrade.
   unattended_remove_unused_dependencies: true
